# Generated by Django 2.2.3 on 2019-07-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20190724_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='option_1',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='option_4',
        ),
    ]
