# Generated by Django 2.2.3 on 2019-07-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizappuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='quizappuser',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='quizappuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
