# Generated by Django 2.2.3 on 2019-08-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
