# Generated by Django 2.2.3 on 2019-08-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20190804_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.Quiz'),
            preserve_default=False,
        ),
    ]
