# Generated by Django 2.2.3 on 2019-08-05 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_guess_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='answer_given',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Choice'),
        ),
    ]
