# Generated by Django 2.2.3 on 2019-09-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20190805_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=50)),
                ('routing_key', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
